//! The About & licenses screen: the build version, punktfunk's own licence, and the
//! generated third-party notices, as one scrollable wall of text. The card chrome is
//! drawn here; the document body is its own scroll-content tile, composited separately.
//! Logic lives in `app::state::about`.
//!
//! **Scrolling is hardware-accelerated, the same way the Settings modal's row list is.**
//! `THIRD-PARTY-NOTICES.txt` wraps to ~12,000 visual lines, far too tall to bake into one
//! GPU texture, so About needs a *windowed* content tile where Settings' 9 rows fit in
//! one. [`wrap_document`] wraps the document once, up front, into a flat list of visual
//! lines with a uniform stride — the unit `ui::scroll::ScrollWindow`/`ui::scroll::ContentWindow` scroll
//! over — and [`draw_window`] rasterizes only a bounded slice at a time (uncached; see
//! `ui::draw_text_uncached`). Scrolling within that slice is a pure `DrawCmd::TexCropped`.
use crate::core::VERSION;
use crate::ui;
use crate::ui::render::Rect;
use crate::ui::text::FontId;
use crate::ui::text::Fonts;
use crate::ui::text::TextRaster;
use crate::ui::Canvas;
use crate::ui::ModalScreen;
use anyhow::Result;

pub const TITLE: &str = "About & licenses";

pub fn subtitle() -> String {
    format!("Version {VERSION}")
}

/// punktfunk-webos' own licence, both halves of the `MIT OR Apache-2.0` dual grant.
const APP_LICENSE: &str = concat!(
    include_str!("../../../LICENSE-MIT"),
    "\n\n=============================== Apache-2.0 ===============================\n\n",
    include_str!("../../../LICENSE-APACHE"),
);

/// Third-party notices for every crate that links on the webOS target, plus the
/// bundled non-Rust components. Generated by `build.rs` during compilation — regenerate
/// (via `task notices`) whenever the dependency tree changes.
const THIRD_PARTY_NOTICES: &str = include_str!("../../../THIRD-PARTY-NOTICES.txt");

/// The whole document, as one static line list. `include_str!` gives a `&'static str`,
/// so splitting it costs one `Vec` of string slices — no copying of the ~560 KB body.
pub fn lines() -> Vec<&'static str> {
    let mut out = vec![
        "punktfunk for webOS",
        "",
        "A native LG webOS TV client for punktfunk — low-latency desktop and",
        "game streaming. Built on the upstream punktfunk project; all credit for",
        "the protocol, FEC/crypto core, and host implementation belongs there.",
        "",
        "  https://github.com/dyptan-io/punktfunk-webos",
        "  https://git.unom.io/unom/punktfunk",
        "",
        "Licensed under MIT OR Apache-2.0, at your option.",
        "",
        "========================================================================",
        "PUNKTFUNK-WEBOS LICENCE",
        "========================================================================",
        "",
    ];
    out.extend(APP_LICENSE.lines());
    out.push("");
    out.extend(THIRD_PARTY_NOTICES.lines());
    out
}

pub const WIDTH_FRAC: f32 = 0.78;
/// Fraction of the panel height the card occupies — tall, since this is a reading page.
const HEIGHT_FRAC: f32 = 0.84;
const SIDE_PAD: u32 = 40;
/// Gap between the header's last line and the first body line.
const HEADER_GAP: u32 = 20;
/// Space left below the last body line, inside the card.
const BOTTOM_PAD: u32 = 28;
/// Vertical gap between rendered lines, on top of the font's own height.
const LINE_GAP: i32 = 4;

pub fn card_rect(screen_w: u32, screen_h: u32) -> Rect {
    let height = (screen_h as f32 * HEIGHT_FRAC).round() as u32;
    ui::widgets::modal_card_rect(screen_w, screen_h, WIDTH_FRAC, height)
}

/// The scrolling viewport inside `card`: whatever the header and the bottom pad leave.
pub fn body_rect(card: Rect, fonts: &Fonts) -> Rect {
    let header_h = (ui::text::modal_header_end_y(fonts, card, SUBTITLE_PROBE) - card.y()).max(0) as u32;
    let body = ui::layout::Layout::vertical([
        ui::layout::Constraint::Length(header_h + HEADER_GAP),
        ui::layout::Constraint::Fill(1),
        ui::layout::Constraint::Length(BOTTOM_PAD),
    ])
    .split(card)[1];
    ui::layout::Layout::horizontal([
        ui::layout::Constraint::Length(SIDE_PAD),
        ui::layout::Constraint::Fill(1),
        ui::layout::Constraint::Length(SIDE_PAD),
    ])
    .split(body)[1]
}

/// A fixed-length stand-in for the real subtitle when measuring the header's height.
/// The subtitle is `Version <VERSION>` — one line at every realistic version string —
/// so the body rect stays put regardless of what the build stamped in.
const SUBTITLE_PROBE: &str = "Version 0.0.0+git.00000000";

/// Stride (px) between two consecutive wrapped visual lines at `font`'s size —
/// the uniform unit `ui::scroll::ScrollWindow`/`ui::scroll::ContentWindow` scroll over.
pub fn line_stride(raster: &dyn TextRaster, font: FontId) -> i32 {
    raster.height(font) + LINE_GAP
}

/// How many wrapped visual lines fit in `body` — used to clamp scrolling so the
/// page can't be scrolled past its own end.
pub fn visible_lines(body: Rect, raster: &dyn TextRaster, font: FontId) -> usize {
    (body.height() as i32 / line_stride(raster, font).max(1)).max(1) as usize
}

/// Wraps every source `line` to `width`, flattening into one list of visual
/// lines — a blank source line becomes one blank visual line (preserving its
/// paragraph gap), and a wrapped one expands to as many entries as it needs.
/// This is the one-time cost (text measurement, not rasterization) that gives
/// the whole document a uniform per-line stride, so it can scroll exactly like
/// Settings' fixed-height rows instead of needing per-source-line bookkeeping.
pub fn wrap_document(raster: &dyn TextRaster, font: FontId, lines: &[&str], width: u32) -> Vec<String> {
    let mut out = Vec::new();
    for line in lines {
        if line.trim().is_empty() {
            out.push(String::new());
        } else {
            // Wrapped, not clipped: this is licence text, and silently truncating it
            // would hide terms the screen exists to display.
            out.extend(ui::text::wrap_text(raster, font, line, width));
        }
    }
    out
}

/// Draws wrapped visual lines `[start, start+len)` of `lines`, top-aligned at
/// this painter's own origin — the content tile's local space, which the GPU
/// compositor then crops/positions from (see `Tile::ScrollContent`'s docs).
/// Only called when `ui::scroll::ContentWindow` (re)bakes a window, not per frame.
pub fn draw_window(c: &mut Canvas, font: FontId, lines: &[String], start: usize, len: usize) -> Result<()> {
    let step = line_stride(c.fonts.raster, font);
    for (i, line) in lines.iter().skip(start).take(len).enumerate() {
        if line.is_empty() {
            continue;
        }
        c.text_uncached(font, line, 0, i as i32 * step, ui::style::theme().muted)?;
    }
    Ok(())
}

/// The About document as a [`ModalScreen`]. Its scrolling body is a separate content
/// tile (see the module docs), so the shell is chrome plus header only.
pub(crate) struct Modal;

impl ModalScreen for Modal {
    fn card_rect(&self, screen_w: u32, screen_h: u32, _fonts: &Fonts) -> Rect {
        card_rect(screen_w, screen_h)
    }

    fn render(&self, c: &mut Canvas, hover_close: bool) -> Result<()> {
        let card = self.card_rect(c.screen_w, c.screen_h, c.fonts);
        c.modal_shell(card, hover_close)?;
        c.modal_header(
            card,
            TITLE,
            ui::style::theme().text,
            &subtitle(),
            ui::style::theme().muted,
        )?;
        Ok(())
    }
}
